// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/healtronlabs/gofasta/app/di/providers"
	"github.com/healtronlabs/gofasta/app/graphql/resolvers"
	"github.com/healtronlabs/gofasta/app/repositories"
	"github.com/healtronlabs/gofasta/app/rest/controllers"
	"github.com/healtronlabs/gofasta/app/services"
	"github.com/healtronlabs/gofasta/app/validators"
	"github.com/healtronlabs/gofasta/configs"
	"github.com/healtronlabs/gofasta/pkg/logger"
)

// Injectors from wire.go:

// InitializeServiceContainer builds the full dependency graph at compile time.
func InitializeServiceContainer() (*ServiceContainer, error) {
	appConfig, err := configs.LoadConfig()
	if err != nil {
		return nil, err
	}
	databaseConfig := providers.ProvideDBConfig(appConfig)
	db := configs.SetupDB(databaseConfig)
	logConfig := providers.ProvideLogConfig(appConfig)
	slogLogger := logger.NewLogger(logConfig)
	appValidator := validators.NewAppValidator(db)
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(db, userRepository, appValidator)
	userController := controllers.NewUserControllerInstance(userService)
	resolver := resolvers.NewResolver(userService)
	serviceContainer := &ServiceContainer{
		Config:         appConfig,
		DB:             db,
		Logger:         slogLogger,
		Validator:      appValidator,
		UserRepo:       userRepository,
		UserService:    userService,
		UserController: userController,
		Resolver:       resolver,
	}
	return serviceContainer, nil
}
