// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/healtronlabs/gofasta/app/di/providers"
	"github.com/healtronlabs/gofasta/app/graphql/resolvers"
	"github.com/healtronlabs/gofasta/app/repositories"
	"github.com/healtronlabs/gofasta/app/rest/controllers"
	"github.com/healtronlabs/gofasta/app/services"
	"github.com/healtronlabs/gofasta/app/validators"
	"github.com/healtronlabs/gofasta/configs"
	"github.com/healtronlabs/gofasta/pkg/auth"
	"github.com/healtronlabs/gofasta/pkg/cache"
	"github.com/healtronlabs/gofasta/pkg/logger"
	"github.com/healtronlabs/gofasta/pkg/mailer"
	"github.com/healtronlabs/gofasta/pkg/queue"
	"github.com/healtronlabs/gofasta/pkg/storage"
)

// Injectors from wire.go:

// InitializeServiceContainer builds the full dependency graph at compile time.
func InitializeServiceContainer() (*ServiceContainer, error) {
	appConfig, err := configs.LoadConfig()
	if err != nil {
		return nil, err
	}
	databaseConfig := providers.ProvideDBConfig(appConfig)
	db := configs.SetupDB(databaseConfig)
	logConfig := providers.ProvideLogConfig(appConfig)
	slogLogger := logger.NewLogger(logConfig)
	appValidator := validators.NewAppValidator(db)
	emailConfig := providers.ProvideEmailConfig(appConfig)
	templateRenderer := providers.ProvideTemplateRenderer(appConfig)
	emailSender, err := mailer.NewEmailSender(emailConfig, templateRenderer, slogLogger)
	if err != nil {
		return nil, err
	}
	cacheConfig := providers.ProvideCacheConfig(appConfig)
	cacheService, err := cache.NewCacheService(cacheConfig, slogLogger)
	if err != nil {
		return nil, err
	}
	authConfig := providers.ProvideAuthConfig(appConfig)
	jwtService := auth.NewJWTService(authConfig)
	rbacService, err := auth.NewRBACService(authConfig)
	if err != nil {
		return nil, err
	}
	storageConfig := providers.ProvideStorageConfig(appConfig)
	storageService, err := storage.NewStorageService(storageConfig, slogLogger)
	if err != nil {
		return nil, err
	}
	queueConfig := providers.ProvideQueueConfig(appConfig)
	queueService, err := queue.NewQueueService(queueConfig, slogLogger)
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository, appValidator)
	userController := controllers.NewUserControllerInstance(userService)
	resolver := resolvers.NewResolver(userService)
	serviceContainer := &ServiceContainer{
		Config:         appConfig,
		DB:             db,
		Logger:         slogLogger,
		Validator:      appValidator,
		EmailSender:    emailSender,
		CacheService:   cacheService,
		JWTService:     jwtService,
		RBACService:    rbacService,
		StorageService: storageService,
		QueueService:   queueService,
		UserRepo:       userRepository,
		UserService:    userService,
		UserController: userController,
		Resolver:       resolver,
	}
	return serviceContainer, nil
}
