services:
  gofasta_go:
    build:
      context: .
      dockerfile: deployments/dev/app/dockerfile
      target: ${PROJECT_NAME}_api_build_dev
    image: ${PROJECT_NAME}_web_image_dev:latest
    container_name: ${PROJECT_NAME}_web_container_dev
    env_file:
      - "./.env"
    volumes:
      - type: bind
        source: .
        target: /gofasta
    ports:
      - $PORT:$PORT
    entrypoint: ["deployments/dev/app/dev_entrypoint.sh"]
    networks:
      - ${DOCKER_NETWORK_NAME}
    restart: always
    profiles:
      - main

  gofasta_postgres:
    build:
      context: .
      dockerfile: deployments/dev/db/dockerfile
      target: ${PROJECT_NAME}_db_build_dev
    image: ${PROJECT_NAME}_db_image_dev
    container_name: ${PROJECT_NAME}_db_container_dev
    environment:
      POSTGRES_USER: ${PROJECT_NAME}
      POSTGRES_PASSWORD: ${PROJECT_NAME}
      POSTGRES_DB: ${PROJECT_NAME}_development
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    networks:
      - ${DOCKER_NETWORK_NAME}
    restart: always
    profiles:
      - db

networks:
  healtron_network:
    external: true

volumes:
  postgres_data:
    driver: local
