# OBJECT TYPES FOR OUTPUT
type User {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  firstName: String!
  otherNames: String!
  email: String!
  phoneNumber: String!
}

type UsersResponseDto {
  users: [User!]!
  pagination: TPaginationObjectDto!
}

# QUERIES
extend type Query {
  users(filters: UserFiltersDto!): UsersResponseDto!
}

# MUTATIONS
extend type Mutation {
  createUser(input: NewUserDto!): User!
}

# INPUTS
input NewUserDto {
  firstName: String!
  otherNames: String!
  email: String!
  phoneNumber: String!
}

input UserFieldsForFiltersDto {
  firstName: String
  otherNames: String
  email: String
  phoneNumber: String
}

input UserFiltersDto {
  fields: UserFieldsForFiltersDto!
  pagination: TPaginationInputDto
  sorting: TSortingInputDto
}
