type User {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  firstName: String!
  otherNames: String!
  email: String!
  phoneNumber: String!
}

extend type Query {
  users: [User!]!
}

input NewUserDto {
  firstName: String!
  otherNames: String!
  email: String!
  phoneNumber: String!
}

extend type Mutation {
  createUser(input: NewUserDto!): User!
}
