services:
  gofasta_postgres_qa:
    build:
      context: .
      dockerfile: dockerfile
      target: ${PROJECT_NAME}_db_build_${ENV}
    image: ${PROJECT_NAME}_db_image_${ENV}
    container_name: ${PROJECT_NAME}_db_container_${ENV}
    environment:
      POSTGRES_USER: ${PROJECT_NAME}
      POSTGRES_PASSWORD: ${PROJECT_NAME}
      POSTGRES_DB: ${PROJECT_NAME}_${ENV}
    volumes:
      - type: bind
        source: /var/lib/docker/volumes/.healtron_live_databases/${PROJECT_NAME}/postgresql/${ENV}
        target: /var/lib/postgresql
    ports:
      - ${DB_HOST_PORT}:${DB_INTERNAL_PORT}
    networks:
      - ${DOCKER_NETWORK_NAME}
    restart: always
    profiles:
      - db

networks:
  healtron_network_qa:
    external: true
