package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/healtronlabs/go-gql-template/app"
)

// MutationHealth is the resolver for the mutationHealth field.
func (r *mutationResolver) MutationHealth(ctx context.Context) (string, error) {
	return "The mutation is healthy!", nil
}

// QueryHealth is the resolver for the queryHealth field.
func (r *queryResolver) QueryHealth(ctx context.Context) (string, error) {
	return "The query is healthy", nil
}

// Mutation returns app.MutationResolver implementation.
func (r *Resolver) Mutation() app.MutationResolver { return &mutationResolver{r} }

// Query returns app.QueryResolver implementation.
func (r *Resolver) Query() app.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
