package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/healtronlabs/go_gql_template/app"
	"github.com/healtronlabs/go_gql_template/app/graphql/goTypes"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input goTypes.NewUser) (*goTypes.User, error) {
	return r.UserService.CreateUser(input)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*goTypes.User, error) {
	return r.UserService.GetUsers()
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *goTypes.User) (string, error) {
	return obj.Id.String(), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *goTypes.User) (string, error) {
	return obj.CreatedAt.String(), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *goTypes.User) (string, error) {
	return obj.UpdatedAt.String(), nil
}

// FirstName is the resolver for the firstName field.
func (r *userResolver) FirstName(ctx context.Context, obj *goTypes.User) (string, error) {
	panic(fmt.Errorf("not implemented: FirstName - firstName"))
}

// OtherNames is the resolver for the otherNames field.
func (r *userResolver) OtherNames(ctx context.Context, obj *goTypes.User) (string, error) {
	panic(fmt.Errorf("not implemented: OtherNames - otherNames"))
}

// Email is the resolver for the email field.
func (r *userResolver) Email(ctx context.Context, obj *goTypes.User) (string, error) {
	panic(fmt.Errorf("not implemented: Email - email"))
}

// PhoneNumber is the resolver for the phoneNumber field.
func (r *userResolver) PhoneNumber(ctx context.Context, obj *goTypes.User) (string, error) {
	panic(fmt.Errorf("not implemented: PhoneNumber - phoneNumber"))
}

// User returns app.UserResolver implementation.
func (r *Resolver) User() app.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
