package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/healtronlabs/go_gql_template/app"
	"github.com/healtronlabs/go_gql_template/app/graphql/goTypes"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input goTypes.NewUserDto) (*goTypes.User, error) {
	return r.UserService.CreateUser(input)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, filters goTypes.UserFiltersDto) ([]*goTypes.User, error) {
	return r.UserService.GetUsers(filters)
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *goTypes.User) (string, error) {
	return obj.Id.String(), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *goTypes.User) (string, error) {
	return obj.CreatedAt.String(), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *goTypes.User) (string, error) {
	return obj.UpdatedAt.String(), nil
}

// User returns app.UserResolver implementation.
func (r *Resolver) User() app.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
type userFiltersDtoResolver struct{ *Resolver }
