package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/healtronlabs/go_gql_template/app/graphql/dtos"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input dtos.NewUserDto) (*dtos.UserResponseDto, error) {
	return r.UserService.CreateUser(input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input dtos.UserFieldsForUpdateDto) (*dtos.UserResponseDto, error) {
	return r.UserService.UpdateUser(input)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, filters dtos.UserFiltersDto) (*dtos.UsersResponseDto, error) {
	return r.UserService.GetUsers(filters)
}
