// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dtos

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type Mutation struct {
}

type Query struct {
}

type TCommonAPIErrorDto struct {
	FieldName *string `json:"fieldName,omitempty"`
	Message   string  `json:"message"`
}

type TCommonResponseDto struct {
	Status  int                   `json:"status"`
	Message *string               `json:"message,omitempty"`
	Errors  []*TCommonAPIErrorDto `json:"errors,omitempty"`
}

type TPaginationObjectDto struct {
	TotalRecords   *int `json:"totalRecords,omitempty"`
	RecordsPerPage *int `json:"recordsPerPage,omitempty"`
	TotalPages     *int `json:"totalPages,omitempty"`
	CurrentPage    *int `json:"currentPage,omitempty"`
}

type TUserResponseDto struct {
	Data   *User                 `json:"data,omitempty"`
	Errors []*TCommonAPIErrorDto `json:"errors,omitempty"`
}

type TUsersResponseDto struct {
	Data       []*User               `json:"data"`
	Pagination *TPaginationObjectDto `json:"pagination"`
}

type User struct {
	ID            uuid.UUID  `json:"id"`
	RecordVersion int        `json:"recordVersion"`
	CreatedAt     time.Time  `json:"createdAt"`
	UpdatedAt     time.Time  `json:"updatedAt"`
	FirstName     string     `json:"firstName"`
	OtherNames    string     `json:"otherNames"`
	Email         string     `json:"email"`
	PhoneNumber   string     `json:"phoneNumber"`
	IsActive      bool       `json:"isActive"`
	IsDeletable   bool       `json:"isDeletable"`
	DeletedAt     *time.Time `json:"deletedAt,omitempty"`
}

type SortOrientation string

const (
	SortOrientationAsc  SortOrientation = "ASC"
	SortOrientationDesc SortOrientation = "DESC"
)

var AllSortOrientation = []SortOrientation{
	SortOrientationAsc,
	SortOrientationDesc,
}

func (e SortOrientation) IsValid() bool {
	switch e {
	case SortOrientationAsc, SortOrientationDesc:
		return true
	}
	return false
}

func (e SortOrientation) String() string {
	return string(e)
}

func (e *SortOrientation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrientation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrientation", str)
	}
	return nil
}

func (e SortOrientation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrientation) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrientation) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
