// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dtos

import (
	"fmt"
	"io"
	"strconv"
)

type Mutation struct {
}

type Query struct {
}

type TCommonAPIErrorDto struct {
	FieldName *string `json:"fieldName,omitempty"`
	Message   string  `json:"message"`
}

type TPaginationObjectDto struct {
	TotalRecords   *int `json:"totalRecords,omitempty"`
	RecordsPerPage *int `json:"recordsPerPage,omitempty"`
	TotalPages     *int `json:"totalPages,omitempty"`
	CurrentPage    *int `json:"currentPage,omitempty"`
}

type TSortingInputDto struct {
	SortByField     string           `json:"sortByField"`
	SortOrientation *SortOrientation `json:"sortOrientation,omitempty"`
}

type User struct {
	ID          string `json:"id"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
	FirstName   string `json:"firstName"`
	OtherNames  string `json:"otherNames"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
}

type UserFieldsForFiltersDto struct {
	FirstName   *string `json:"firstName,omitempty"`
	OtherNames  *string `json:"otherNames,omitempty"`
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

type UserFieldsForUpdateDto struct {
	ID          string  `json:"id"`
	FirstName   *string `json:"firstName,omitempty"`
	OtherNames  *string `json:"otherNames,omitempty"`
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

type UserFiltersDto struct {
	Fields     *UserFieldsForFiltersDto `json:"fields"`
	Pagination *TPaginationInputDto     `json:"pagination,omitempty"`
	Sorting    *TSortingInputDto        `json:"sorting,omitempty"`
}

type UserResponseDto struct {
	Data   *User                 `json:"data,omitempty"`
	Errors []*TCommonAPIErrorDto `json:"errors,omitempty"`
}

type UsersResponseDto struct {
	Users      []*User               `json:"users"`
	Pagination *TPaginationObjectDto `json:"pagination"`
}

type SortOrientation string

const (
	SortOrientationAsc  SortOrientation = "ASC"
	SortOrientationDesc SortOrientation = "DESC"
)

var AllSortOrientation = []SortOrientation{
	SortOrientationAsc,
	SortOrientationDesc,
}

func (e SortOrientation) IsValid() bool {
	switch e {
	case SortOrientationAsc, SortOrientationDesc:
		return true
	}
	return false
}

func (e SortOrientation) String() string {
	return string(e)
}

func (e *SortOrientation) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrientation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrientation", str)
	}
	return nil
}

func (e SortOrientation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
