# Stage 1: Build
FROM golang:1.22.5-alpine3.20 AS gofasta_api_build_qa
WORKDIR /gofasta
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o gofasta ./app/main 

# Stage 2: Final Image
FROM golang:1.22.5-alpine3.20
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.16.2
ARG ENV
ENV ENV=${ENV}

WORKDIR /gofasta

# Copy the built application from the build stage
COPY --from=gofasta_api_build_qa /gofasta .

# Set the entrypoint script
COPY ./deployments/${ENV}/app/${ENV}_entrypoint.sh /gofasta/entrypoint.sh
RUN chmod +x /gofasta/entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/gofasta/entrypoint.sh"]
