scalar DateTime

enum SortOrientation {
    ASC
    DESC
}

# INPUTS
input TPaginationInputDto {
    limit: Int = 10
    page: Int = 1
}

input TSortingInputDto {
    sortByField: String!
    sortOrientation: SortOrientation = DESC
}

# OBJECTS
type TPaginationObjectDto {
    totalRecords: Int
    recordsPerPage: Int
    totalPages: Int
    currentPage: Int
}

type TCommonApiErrorDto {
    fieldName: String
    message: String!
}
